// Demo scenario registry — the carousel cards beside the phone, matching the
// hero site's "Real Scenarios". Selecting one drives the mock backend AND
// prefills the send flow so a run is one tap on stage.

export const DEMO_SCENARIOS = [
  {
    key: 'grandparent',
    emoji: '🧓',
    tag: 'GRANDPARENT SCAM',
    tone: 'red',
    title: '9 PM. Phone call. Grandchild needs bail.',
    story: 'A caller poses as a grandchild in jail needing $2,000 via Zelle immediately. The customer is panicked, heart racing, following instructions.',
    rail: 'Zelle',
    payee: 'michael.easter@zellemail.com',
    amount: 2000,
    expect: 'VERIFY',
  },
  {
    key: 'remote',
    emoji: '💻',
    tag: 'REMOTE ACCESS TAKEOVER',
    tone: 'blue',
    title: 'Tech support call. Screen shared. Bot in control.',
    story: 'A fraudster has remote access. Machine-speed typing, ruler-straight cursor, instant field fills — far outside the customer’s own pattern.',
    rail: 'Wire',
    payee: 'michael.easter@zellemail.com',
    amount: 5200,
    expect: 'PAUSE',
  },
  {
    key: 'impaired',
    emoji: '🌙',
    tag: 'IMPAIRED DECISION',
    tone: 'violet',
    title: '2 AM. Party. Irreversible transfer.',
    story: 'A young adult sends $500 to someone they just met. Erratic typing, mis-taps, first-time payee, round amount — and Zelle can’t be undone.',
    rail: 'Zelle',
    payee: 'michael.easter@zellemail.com',
    amount: 500,
    expect: 'STEP UP',
  },
  {
    key: 'workout',
    emoji: '🏋️',
    tag: 'FALSE-POSITIVE GUARD',
    tone: 'green',
    title: '6 PM. Mid-workout. Heart racing.',
    story: 'Heart rate 121 — the same number that flags coercion. One Shield reads the setting and clears it: exercise, not fear.',
    rail: 'Zelle',
    payee: 'rich.fairbank@zellemail.com',
    amount: 120,
    expect: 'APPROVE',
  },
  {
    key: 'normal',
    emoji: '✅',
    tag: 'EVERYDAY PAYMENT',
    tone: 'green',
    title: 'Tuesday afternoon. Familiar payee.',
    story: 'A routine $60 to a payee used every month. One Shield clears it with the free on-device checks — and skips what it doesn’t need.',
    rail: 'Zelle',
    payee: 'rich.fairbank@zellemail.com',
    amount: 60,
    expect: 'APPROVE',
  },
  {
    key: 'no_consent',
    emoji: '🔒',
    tag: 'PRIVACY CHOICE',
    tone: 'blue',
    title: 'First run. Customer says “Don’t allow.”',
    story: 'Health data declined up front. Mid-run, One Shield offers a one-time reading — declining never blocks the money; sharing makes it seamless.',
    rail: 'Zelle',
    payee: 'michael.easter@zellemail.com',
    amount: 950,
    expect: 'ONE-TIME ASK',
  },
]
